[project]
name = "latencysim"
version = "0.1.0"
description = "Latency simulator"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "mypy>=1.14.1",
    "ruff>=0.8.6",
]
